services:
  db:
    image: mysql
    container_name: microservice
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - microservice_data:/var/lib/mysql

volumes:
  microservice_data: